### ISSUE TITLE
duplicate copies of water administration posting after queue commits

### ISSUE THREAD

**Issue by northerlywind** [cortex-lab/alyx-matlab#18]
multiple, duplicate copies of water administration are posted after being held in a queue

**Comment by petersaj** [comment]
I saw that yesterday from Miles I think - it looked like it was posting water 6 times. that's not a queuing error, it looked like that was an error in MC interfacing with alyx, I was going to take a look but the rigs were being used so could troubleshoot. 

happy to take a look at it today whenever but I don't think that's a flushQueue error

**Comment by northerlywind** [comment]
I personally had postings of 30+ duplicates but sure, thanks

**Comment by rossant** [comment]
I don't know if that's related, but I fixed a bug 2 days ago in alyx's admin interface where a model was saved 6 or 7 times instead of once. I don't know if alyx has been updated on the server since then. Maybe the current bug is unrelated to this one.

**Comment by nsteinme** [comment]
Ok, but this is working normally on my rig computer. Julie could you try
running eui.alyxGUI from your desktop and see if a water posting from there
is replicated? I suspect instead this is about Miles's modifications on the
training box computer, which aren't yet part of the repository.

**Comment by northerlywind** [comment]
it's never a problem with the alyxGUI - afaik, hydrogel postings are fine - it's specifically the water postings that occur at the end of the experiment that are duplicated, so I can't test that right now unfortunately.

**Comment by nsteinme** [comment]
Ah. That is code I didn't write. Please ask @k1o0.

**Comment by northerlywind** [comment]
I know, I asked already and he wasn't sure but it was something that came up after the recent commits regarding the queue, hence would be useful if @petersaj could take a look together with him

**Comment by nsteinme** [comment]
@rossant what was the situation under which multiple posts were happening?
Maybe we can test for that situation? And should we update the server code?

**Comment by rossant** [comment]
The same SQL save command was executed six times or so whenever a change was made in a subject. It didn't result in duplication of entries. The only side-effect was when an email was sent after a change of responsible user, which might have happened several times at once.

It might be wiser to wait until no one actively uses the database to update it? Maybe an evening? We can't rule out an unexpected problem when updating.

**Comment by nsteinme** [comment]
ok, note to @petersaj @k1o0 @northerlywind - alyx.cortexlab.net will be updated with latest code Monday morning, but alyx-dev has the most current code so you could test using that if you think it might be an alyx-side issue related to the thing cyrille fixed recently.

**Comment by nsteinme** [comment]
(though it very much sounds like it is not)

**Comment by petersaj** [comment]
if someone wants to grab me and replicate the problem I'll look into it -
it sounds 95% like it's an MC interface problem though right?

**Comment by nsteinme** [comment]
I hope this has been resolved, @northerlywind @petersaj @k1o0 let me know if you see it again?

**Comment by northerlywind** [comment]
the same or similar queueing issue happened using alyx-matlab at the end of a T-maze task, so I'd say it wasn't resolved. it might not be a bug, but if someone knows how to avoid this happening I'd appreciate it!

**Comment by nsteinme** [comment]
Hi Julie, could you provide more details about what command was run and
what the error message was? I've never seen this replicated, I'm confused
about it. Thanks -
